Регистрация:
<form action="/user/register" method="post">
    Имя: <input type="text" name="username"> <br>
    Пароль: <input type="password" name="password"> <br>
    Подтверждение пароля: <input type="password" name="password_check"> <br>
    E-mail: <input type="email" name="email"> <br>
    <input type="submit" value="Зарегистрироваться">
</form>
<br>
<br>

Войти
<form action="/user/login" method="post">
    E-mail: <input type="email" name="email"> <br>
    Пароль: <input type="password" name="password"> <br>
    <input type="submit" value="Войти">
</form>

<br>
<br>
<?php if($this->error): ?>
    <span style="color: red"><?=$this->error;?></span>
<?php endif; ?>